name: pompe
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.3
  - bioconductor-affy
  - bioconductor-limma
  - bioconductor-hgu133plus2.db
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
  - bioconductor-multimir
  - bioconductor-stringdb
  - bioconductor-enrichplot
  - bioconductor-dose
  - bioconductor-gosemsim
  - r-data.table
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-jsonlite
  - r-ggrepel
  - r-umap
  - r-tidygraph
  - r-rdgidb

   - pip
  - pip:
      - pre-commit
